name: 'Repo Performance'
author: 'ToyB0x'
description: 'Analyze repository metrics'
branding:
  color: 'blue'
  icon: 'activity'
inputs:
  CLI_VERSION:
    description: "ts-bench CLI version to use for analysis"
    required: false
    default: "0.0.19"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm install -g tsx
      shell: bash

      # NOTE: Must pin version to avoid breaking changes
    - name: Run migrations
      run: npx @ts-bench/cli@${{ inputs.CLI_VERSION }} db migrate
      shell: bash
      env:
        DB_FILE_NAME: "ts-bench.sqlite"

      # NOTE: Must pin version to avoid breaking changes
    - name: Run performance analysis
      run: npx @ts-bench/cli@${{ inputs.CLI_VERSION }} analyze > report.md
      shell: bash
      env:
        DB_FILE_NAME: "ts-bench.sqlite"
