name: Changesets

on:
  push:
    branches:
      - main

env:
  CI: true

permissions:
  contents: write # to create release pull request
  issues: write # to create issues for unreleased changes
  pull-requests: write # to create pull requests for changesets

jobs:
  version:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup & Restore Node cache
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'

      - name: Install all packages
        run: pnpm install --frozen-lockfile

      - name: Prepare test env
        run: cp .env.example .env

      - name: Build
        run: pnpm build
        env:
          DB_FILE_NAME: ${{ github.workspace }}/temp.db

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1.5.3
        with:
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
